import type { CalendarEvent } from './calendar-types'

export const events: CalendarEvent[] = [
  {
    calendar: 'focus',
    color: 'violet',
    day: '2026-08-10',
    duration: 90,
    id: 'event-focus',
    note: 'Finish the instant-navigation test cases before lunch.',
    start: '09:00',
    title: 'Focus time',
  },
  {
    calendar: 'team',
    color: 'blue',
    day: '2026-08-10',
    duration: 45,
    id: 'event-standup',
    start: '11:00',
    title: 'Product standup',
  },
  {
    calendar: 'personal',
    color: 'rose',
    day: '2026-08-11',
    duration: 60,
    id: 'event-design-review',
    note: 'Review the new app shell and calendar density.',
    start: '10:30',
    title: 'Design review',
  },
  {
    calendar: 'team',
    color: 'amber',
    day: '2026-08-12',
    duration: 30,
    id: 'event-office-hours',
    start: '13:00',
    title: 'Office hours',
  },
  {
    calendar: 'focus',
    color: 'violet',
    day: '2026-08-13',
    duration: 90,
    id: 'event-deep-work',
    start: '08:30',
    title: 'Writing block',
  },
  {
    calendar: 'personal',
    color: 'blue',
    day: '2026-08-14',
    duration: 45,
    id: 'event-coffee',
    start: '12:00',
    title: 'Coffee with Mira',
  },
]
